CREATE TABLE membership_periods (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 public_id BINARY(16) NOT NULL UNIQUE,
 membership_id BIGINT NOT NULL,
 period_year SMALLINT NOT NULL,
 period_month TINYINT NOT NULL,
 coverage_start DATE NOT NULL,
 coverage_end_exclusive DATE NOT NULL,
 plan_id BIGINT NOT NULL,
 plan_name_snapshot VARCHAR(120) NOT NULL,
 amount_snapshot DECIMAL(12,2) NOT NULL,
 currency_snapshot CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 accreditation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 accredited_at TIMESTAMP(6) NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 CONSTRAINT uq_membership_month UNIQUE (membership_id, period_year, period_month),
 CONSTRAINT fk_membership_period_member FOREIGN KEY (membership_id) REFERENCES paid_memberships(id),
 CONSTRAINT fk_membership_period_plan FOREIGN KEY (plan_id) REFERENCES membership_plans(id),
 CONSTRAINT ck_membership_period_month CHECK (period_month BETWEEN 1 AND 12),
 CONSTRAINT ck_membership_period_year CHECK (period_year BETWEEN 2000 AND 9998),
 CONSTRAINT ck_membership_period_amount CHECK (amount_snapshot >= 0),
 CONSTRAINT ck_membership_period_currency CHECK (currency_snapshot REGEXP '^[A-Z]{3}$'),
 CONSTRAINT ck_membership_period_coverage CHECK (coverage_end_exclusive > coverage_start),
 CONSTRAINT ck_membership_calendar CHECK (DAYOFMONTH(coverage_start) = 1 AND YEAR(coverage_start) = period_year AND MONTH(coverage_start) = period_month AND coverage_end_exclusive = DATE_ADD(coverage_start, INTERVAL 1 MONTH)),
 CONSTRAINT ck_membership_accreditation CHECK ((accreditation_status = 'PENDING' AND accredited_at IS NULL) OR (accreditation_status = 'ACCREDITED' AND accredited_at IS NOT NULL)),
 INDEX ix_membership_period_month (period_year, period_month, accreditation_status)
);
