ALTER TABLE membership_periods ADD payment_locked_at TIMESTAMP(6) NULL;
CREATE TABLE membership_payment_attempts (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 public_id BINARY(16) NOT NULL UNIQUE,
 membership_period_id BIGINT NOT NULL UNIQUE,
 idempotency_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 fingerprint BINARY(32) NOT NULL,
 external_reference VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 environment VARCHAR(20) NOT NULL,
 seller_account_id VARCHAR(100) NOT NULL,
 preference_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NULL UNIQUE,
 checkout_url VARCHAR(2000) NULL,
 return_url VARCHAR(2000) NOT NULL,
 technical_status VARCHAR(20) NOT NULL,
 last_error_code VARCHAR(64) NULL,
 expires_at TIMESTAMP(6) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_membership_attempt_period FOREIGN KEY (membership_period_id) REFERENCES membership_periods(id),
 CONSTRAINT ck_membership_attempt_environment CHECK (environment IN ('TEST','PRODUCTION')),
 CONSTRAINT ck_membership_attempt_status CHECK (technical_status IN ('CREATING','CREATED','UNKNOWN','FAILED')),
 CONSTRAINT ck_membership_attempt_preference CHECK (technical_status <> 'CREATED' OR (preference_id IS NOT NULL AND checkout_url IS NOT NULL)),
 INDEX ix_membership_attempt_recovery (technical_status, updated_at)
);
CREATE TABLE membership_payments (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 public_id BINARY(16) NOT NULL UNIQUE,
 membership_period_id BIGINT NOT NULL,
 payment_attempt_id BIGINT NOT NULL,
 provider VARCHAR(30) NOT NULL DEFAULT 'MERCADO_PAGO',
 provider_payment_id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 amount DECIMAL(18,2) NOT NULL,
 currency VARCHAR(10) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 provider_status VARCHAR(40) NOT NULL,
 environment VARCHAR(20) NOT NULL,
 seller_account_id VARCHAR(100) NOT NULL,
 paid_at TIMESTAMP(6) NULL,
 applied_at TIMESTAMP(6) NULL,
 provider_updated_at TIMESTAMP(6) NOT NULL,
 review_reason VARCHAR(64) NULL,
 applied_period_id BIGINT GENERATED ALWAYS AS (CASE WHEN applied_at IS NOT NULL THEN membership_period_id ELSE NULL END) STORED,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT uq_membership_provider_payment UNIQUE (provider,environment,seller_account_id,provider_payment_id),
 CONSTRAINT uq_membership_payment_application UNIQUE (applied_period_id),
 CONSTRAINT fk_membership_payment_period FOREIGN KEY (membership_period_id) REFERENCES membership_periods(id),
 CONSTRAINT fk_membership_payment_attempt FOREIGN KEY (payment_attempt_id) REFERENCES membership_payment_attempts(id),
 CONSTRAINT ck_membership_payment_provider CHECK (provider='MERCADO_PAGO'),
 CONSTRAINT ck_membership_payment_environment CHECK (environment IN ('TEST','PRODUCTION')),
 CONSTRAINT ck_membership_payment_amount CHECK (amount >= 0),
 INDEX ix_membership_payment_period (membership_period_id,updated_at),
 INDEX ix_membership_payment_review (review_reason,updated_at)
);
