CREATE TABLE shipping_carrier_settings (
  id TINYINT PRIMARY KEY,
  provider VARCHAR(30) NOT NULL DEFAULT 'ANDREANI',
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  environment VARCHAR(20) NOT NULL DEFAULT 'SANDBOX',
  client_code VARCHAR(80) NULL,
  contract_code VARCHAR(80) NULL,
  username_key_id VARCHAR(64) NULL,
  username_nonce VARBINARY(32) NULL,
  username_ciphertext VARBINARY(4096) NULL,
  password_key_id VARCHAR(64) NULL,
  password_nonce VARBINARY(32) NULL,
  password_ciphertext VARBINARY(4096) NULL,
  credential_context CHAR(36) NOT NULL,
  origin_postal_code VARCHAR(20) NULL,
  origin_street VARCHAR(160) NULL,
  origin_number VARCHAR(30) NULL,
  origin_city VARCHAR(160) NULL,
  origin_province VARCHAR(160) NULL,
  origin_country VARCHAR(80) NOT NULL DEFAULT 'Argentina',
  sender_name VARCHAR(160) NULL,
  sender_email VARCHAR(254) NULL,
  sender_phone VARCHAR(40) NULL,
  sender_document_type VARCHAR(10) NULL,
  sender_document_number VARCHAR(20) NULL,
  default_weight_grams DECIMAL(10,3) NULL,
  default_length_cm DECIMAL(10,2) NULL,
  default_width_cm DECIMAL(10,2) NULL,
  default_height_cm DECIMAL(10,2) NULL,
  tracking_sync_minutes INT NOT NULL DEFAULT 15,
  version BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CHECK (id = 1),
  CHECK (provider IN ('ANDREANI')),
  CHECK (environment IN ('SANDBOX','PRODUCTION')),
  CHECK (sender_document_type IS NULL OR sender_document_type IN ('DNI','CUIT','CUIL')),
  CHECK (default_weight_grams IS NULL OR default_weight_grams > 0),
  CHECK (default_length_cm IS NULL OR default_length_cm > 0),
  CHECK (default_width_cm IS NULL OR default_width_cm > 0),
  CHECK (default_height_cm IS NULL OR default_height_cm > 0),
  CHECK (tracking_sync_minutes BETWEEN 5 AND 1440)
);

INSERT INTO shipping_carrier_settings(id, credential_context) VALUES (1, UUID());

CREATE TABLE shipping_carrier_quotes (
  id CHAR(36) PRIMARY KEY,
  method_id CHAR(36) NOT NULL,
  provider VARCHAR(30) NOT NULL,
  service_code VARCHAR(80) NULL,
  provider_cost DECIMAL(15,2) NOT NULL,
  shipping_amount DECIMAL(15,2) NOT NULL,
  list_subtotal DECIMAL(15,2) NOT NULL,
  discount_amount DECIMAL(15,2) NOT NULL,
  total DECIMAL(15,2) NOT NULL,
  postal_code VARCHAR(20) NOT NULL,
  weight_grams DECIMAL(10,3) NOT NULL,
  length_cm DECIMAL(10,2) NOT NULL,
  width_cm DECIMAL(10,2) NOT NULL,
  height_cm DECIMAL(10,2) NOT NULL,
  expires_at TIMESTAMP(6) NOT NULL,
  consumed_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHECK (provider IN ('ANDREANI')),
  CHECK (provider_cost >= 0),
  CHECK (shipping_amount >= 0),
  CHECK (weight_grams > 0),
  CHECK (length_cm > 0),
  CHECK (width_cm > 0),
  CHECK (height_cm > 0),
  INDEX ix_shipping_carrier_quotes_expiry (expires_at, consumed_at)
);

ALTER TABLE shipments
  ADD COLUMN provider_cost DECIMAL(15,2) NULL AFTER shipping_cost,
  ADD COLUMN external_reference VARCHAR(160) NULL AFTER provider,
  ADD COLUMN label_reference VARCHAR(160) NULL AFTER external_reference,
  ADD COLUMN provider_status VARCHAR(160) NULL AFTER label_reference,
  ADD COLUMN last_synced_at TIMESTAMP(6) NULL AFTER provider_status,
  ADD COLUMN provider_error VARCHAR(1000) NULL AFTER last_synced_at,
  ADD UNIQUE KEY uk_shipments_provider_external (provider, external_reference),
  ADD CONSTRAINT ck_shipments_provider_cost CHECK (provider_cost IS NULL OR provider_cost >= 0);
