package com.comercioflex.identity.domain;

public enum TenantPermission {
	VIEW_DASHBOARD,
	VIEW_CATALOG,
	MANAGE_CATALOG,
	VIEW_INVENTORY,
	ADJUST_STOCK,
	MANAGE_ORDERS,
	MANAGE_BASIC_SETTINGS,
	MANAGE_MEMBERSHIPS,
	VIEW_RADIO_MEMBERSHIPS,
	MANAGE_RADIO_PLANS,
	MANAGE_PAYMENTS
}
