import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { routeParam } from '../../core/auth/auth.guards';
import { ActivatedRoute } from '@angular/router';
import { RadioProgram, RadioSite, RadioSiteApiService, RadioSponsor, RadioTeamMember } from './radio-site-api.service';

@Component({ selector: 'app-radio-content-admin', imports: [ReactiveFormsModule], styleUrl: './membership.scss', template: `
<section class="radio-admin-content"><h1>Contenido de la radio</h1><p>Configurá la experiencia pública de este tenant RADIO.</p>@if (error()) { <p role="alert">{{ error() }}</p> } @if (saved()) { <p role="status">Cambios guardados.</p> }
<section class="card"><h2>Apariencia y redes</h2><form [formGroup]="settingsForm" (ngSubmit)="saveSettings()"><label>Título del hero<input formControlName="heroTitle" maxlength="160" /></label><label>Subtítulo<textarea formControlName="heroSubtitle" maxlength="300"></textarea></label><label>Descripción<textarea formControlName="description" maxlength="1000"></textarea></label><div class="fields"><label>YouTube<input formControlName="youtubeUrl" type="url" placeholder="https://youtube.com/@tu-radio" /></label><label>ID del canal de YouTube<input formControlName="youtubeChannelId" maxlength="100" placeholder="UC..." /><small class="hint">Se usa para mostrar los últimos videos públicamente.</small></label><label>Instagram<input formControlName="instagramUrl" type="url" /></label><label>X / Twitter<input formControlName="xUrl" type="url" /></label><label>WhatsApp<input formControlName="whatsappUrl" type="url" /></label></div><button [disabled]="busy()" type="submit">Guardar configuración</button></form><p class="hint">Logo, favicon, hero y colores se administran desde Apariencia, reutilizando el almacenamiento existente.</p></section>
<section class="card"><h2>Programas</h2><form [formGroup]="programForm" (ngSubmit)="saveProgram()"><div class="fields"><label>Nombre<input formControlName="name" required /></label><label>Días<input formControlName="days" placeholder="Lunes a viernes" required /></label><label>Horario<input formControlName="schedule" placeholder="18:00 hs" required /></label><label>Conductores<input formControlName="hosts" /></label></div><label>Descripción<textarea formControlName="description" required></textarea></label><label>Imagen URL<input formControlName="imageUrl" type="url" /></label><button [disabled]="busy()" type="submit">Agregar programa</button></form><div class="content-list">@for (item of site()?.programs; track item.publicId) { <article><strong>{{ item.name }}</strong><span>{{ item.days }} · {{ item.schedule }}</span><button type="button" class="secondary" (click)="remove('programs', item.publicId)">Quitar</button></article> }</div></section>
<section class="card"><h2>Equipo</h2><form [formGroup]="teamForm" (ngSubmit)="saveTeam()"><div class="fields"><label>Nombre<input formControlName="name" required /></label><label>Rol<input formControlName="role" required /></label><label>Foto URL<input formControlName="photoUrl" type="url" /></label><label>Redes URL<input formControlName="socialUrl" type="url" /></label></div><label>Bio corta<textarea formControlName="bio" required></textarea></label><button [disabled]="busy()" type="submit">Agregar integrante</button></form><div class="content-list">@for (item of site()?.team; track item.publicId) { <article><strong>{{ item.name }}</strong><span>{{ item.role }}</span><button type="button" class="secondary" (click)="remove('team', item.publicId)">Quitar</button></article> }</div></section>
<section class="card"><h2>Sponsors</h2><form [formGroup]="sponsorForm" (ngSubmit)="saveSponsor()"><div class="fields"><label>Nombre<input formControlName="name" required /></label><label>Logo URL<input formControlName="logoUrl" type="url" /></label><label>URL<input formControlName="targetUrl" type="url" /></label><label>Nivel<select formControlName="level"><option value="PRIMARY">Principal</option><option value="SECONDARY">Secundario</option></select></label></div><label>Texto<textarea formControlName="description"></textarea></label><button [disabled]="busy()" type="submit">Agregar sponsor</button></form><div class="content-list">@for (item of site()?.sponsors; track item.publicId) { <article><strong>{{ item.name }}</strong><span>Sponsor {{ item.level }}</span><button type="button" class="secondary" (click)="remove('sponsors', item.publicId)">Quitar</button></article> }</div></section>
</section>` })
export class RadioContentAdminPage {
  private readonly api = inject(RadioSiteApiService); private readonly route = inject(ActivatedRoute); readonly slug = routeParam(this.route.snapshot, 'storeSlug')!;
  readonly site = signal<RadioSite | null>(null); readonly busy = signal(false); readonly saved = signal(false); readonly error = signal('');
  readonly settingsForm = new FormGroup({ heroTitle: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(160)] }), heroSubtitle: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(300)] }), description: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(1000)] }), youtubeUrl: new FormControl('', { nonNullable: true }), youtubeChannelId: new FormControl('', { nonNullable: true, validators: [Validators.maxLength(100)] }), instagramUrl: new FormControl('', { nonNullable: true }), xUrl: new FormControl('', { nonNullable: true }), whatsappUrl: new FormControl('', { nonNullable: true }) });
  readonly programForm = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(160)] }), description: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(1000)] }), days: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(160)] }), schedule: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.maxLength(120)] }), imageUrl: new FormControl('', { nonNullable: true }), hosts: new FormControl('', { nonNullable: true }) });
  readonly teamForm = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: [Validators.required] }), role: new FormControl('', { nonNullable: true, validators: [Validators.required] }), bio: new FormControl('', { nonNullable: true, validators: [Validators.required] }), photoUrl: new FormControl('', { nonNullable: true }), socialUrl: new FormControl('', { nonNullable: true }) });
  readonly sponsorForm = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: [Validators.required] }), logoUrl: new FormControl('', { nonNullable: true }), targetUrl: new FormControl('', { nonNullable: true }), description: new FormControl('', { nonNullable: true }), level: new FormControl<'PRIMARY' | 'SECONDARY'>('SECONDARY', { nonNullable: true }) });
  constructor() { this.reload(); }
  reload() { this.api.admin(this.slug).subscribe({ next: value => { this.site.set(value); const s = value.settings; this.settingsForm.patchValue({ heroTitle: s.heroTitle ?? '', heroSubtitle: s.heroSubtitle ?? '', description: s.description ?? '', youtubeUrl: s.youtubeUrl ?? '', youtubeChannelId: s.youtubeChannelId ?? '', instagramUrl: s.instagramUrl ?? '', xUrl: s.xUrl ?? '', whatsappUrl: s.whatsappUrl ?? '' }); }, error: () => this.error.set('No pudimos cargar el contenido de la radio.') }); }
  saveSettings() { if (this.busy() || this.settingsForm.invalid) return; this.busy.set(true); this.saved.set(false); this.api.settings(this.slug, this.settingsForm.getRawValue()).pipe(finalize(() => this.busy.set(false))).subscribe({ next: value => { this.site.set(value); this.saved.set(true); }, error: () => this.error.set('No pudimos guardar la configuración.') }); }
  saveProgram() { this.programForm.markAllAsTouched(); if (this.busy() || this.programForm.invalid) return; this.busy.set(true); this.api.saveProgram(this.slug, { ...this.programForm.getRawValue(), imageUrl: this.programForm.value.imageUrl || null, hosts: this.programForm.value.hosts || null, displayOrder: this.site()?.programs.length ?? 0, active: true }).pipe(finalize(() => this.busy.set(false))).subscribe({ next: () => { this.programForm.reset(); this.reload(); }, error: () => this.error.set('No pudimos guardar el programa.') }); }
  saveTeam() { this.teamForm.markAllAsTouched(); if (this.busy() || this.teamForm.invalid) return; this.busy.set(true); this.api.saveTeam(this.slug, { ...this.teamForm.getRawValue(), photoUrl: this.teamForm.value.photoUrl || null, socialUrl: this.teamForm.value.socialUrl || null, displayOrder: this.site()?.team.length ?? 0, active: true }).pipe(finalize(() => this.busy.set(false))).subscribe({ next: () => { this.teamForm.reset(); this.reload(); }, error: () => this.error.set('No pudimos guardar el integrante.') }); }
  saveSponsor() { this.sponsorForm.markAllAsTouched(); if (this.busy() || this.sponsorForm.invalid) return; this.busy.set(true); this.api.saveSponsor(this.slug, { ...this.sponsorForm.getRawValue(), logoUrl: this.sponsorForm.value.logoUrl || null, targetUrl: this.sponsorForm.value.targetUrl || null, description: this.sponsorForm.value.description || null, displayOrder: this.site()?.sponsors.length ?? 0, active: true }).pipe(finalize(() => this.busy.set(false))).subscribe({ next: () => { this.sponsorForm.reset({ level: 'SECONDARY' }); this.reload(); }, error: () => this.error.set('No pudimos guardar el sponsor.') }); }
  remove(kind: 'programs' | 'team' | 'sponsors', id: string) { if (this.busy()) return; this.busy.set(true); this.api.remove(this.slug, kind, id).pipe(finalize(() => this.busy.set(false))).subscribe({ next: () => this.reload(), error: () => this.error.set('No pudimos quitar el contenido.') }); }
}
