spring:
  flyway:
    user: ${MIGRATION_DB_USER}
    password: ${MIGRATION_DB_PASSWORD}

app:
  media:
    storage: s3
  database:
    tenant-migration-enabled: true
    migration-username: ${MIGRATION_DB_USER}
    migration-password: ${MIGRATION_DB_PASSWORD}
